### ISSUE TITLE
Cannot import file using the current EpiVis system

### ISSUE THREAD

**Issue by jingjtang** [cmu-delphi/www-epivis#18]
The current EpiVis system (https://delphi.cmu.edu/epivis/) does not allow importing files.  At least it cannot work using Safari/Chrome/Firefox

However, this one (https://delphi.midas.cs.cmu.edu/epivis/epivis.html)) works. 

From @korlaxxalrok 

_That alternate link at [delphi.midas.cs.cmu.edu](http://delphi.midas.cs.cmu.edu/) will go way soon and eventually redirect to [delphi.cmu.edu](http://delphi.cmu.edu/), but it is interesting that it points to a working system._

**Comment by jingjtang** [comment]
From @brookslogan 

It's just that Firefox doesn't seem to give useful debug info.  It doesn't work on Chromium either, but Chromium does give useful debug.

```
importCSV.ts:79 Uncaught TypeError: Cannot read properties of undefined (reading 'datasets')
    at pi (importCSV.ts:79:23)
    at HTMLFormElement.<anonymous> (ImportCSVDialog.svelte:31:7)
pi @ importCSV.ts:79
(anonymous) @ ImportCSVDialog.svelte:31
```

**Comment by brookslogan** [comment]
From clicking around in devtools:
- Error occurs in the "sibling" case, but for a parentless level-0 `active`
- There appear to be no rows recognized, which may be what prevents a level from being assigned.  The (final value of the) `rows` variable inside `importCSV` seems weird: it just appears to be one long array of entries rather than something 2-D, and contains some bogus-looking entries, e.g., the 6th entrie is "suscep_rateak", splicing together the last colum header and the first entry of the first non-header row.  This may point to the issue being in `csvParseRows` or other processing done to `rows` + unclear error messaging when no rows are recognized inside of `importCSV`.

**Comment by sgratzl** [comment]
@jingjtang do you have a sample CSV file I should test?

**Comment by jingjtang** [comment]
@sgratzl [Here](https://raw.githubusercontent.com/CHENlab-Yale/COVID-Climate/main/Data/EPA-PM25.csv) it is.
